### ISSUE TITLE
Shields not working BUG

### ISSUE THREAD

**Issue by Miner28** [rimworld-frontierdevelopment/Shields#90] opened 2019-09-07 13:53 UTC
When i place down shield it starts spamming error in console and shield doesn't work

Exception ticking Building_ShieldGeneratorLarge555704 (at (145, 0, 198)): System.NullReferenceException: Object reference not set to an instance of an object
  at FrontierDevelopments.Shields.Buildings.Building_ElectricShield.Tick () [0x00000] in <filename unknown>:0 
  at Verse.TickList.Tick () [0x00000] in <filename unknown>:0 
Verse.Log:Error(String, Boolean)
Verse.TickList:Tick()
Verse.TickManager:DoSingleTick()
Verse.TickManager:TickManagerUpdate()
Verse.Game:UpdatePlay()
Verse.Root_Play:Update_Patch1(Object)

**Comment by JonnyNova** [comment] 2019-10-03 12:46
Can you share the full log?

**Comment by JonnyNova** [comment] 2019-10-11 20:13
Duplicate of #90

**Closed by JonnyNova** 2019-10-11 20:13 UTC
Labels: bug, duplicate
